spring: #띄어쓰기 없음
  datasource: #띄어쓰기 2칸
    driver-class-name: com.mysql.cj.jdbc.Driver #띄어쓰기 4칸
    url: jdbc:mysql://localhost:3306/fridge?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8 #띄어쓰기 4칸
    username: root #띄어쓰기 4칸
    password: sojeong0@ #띄어쓰기 4칸
  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: update #띄어쓰기 6칸
    generate-ddl: true #띄어쓰기 4칸
    show-sql: true #띄어쓰기 4칸